common:
    lid_topic: "/ouster/points"
    imu_topic: "/ouster/imu"
    wheel_topic: "/slaver/wheel_state"
    time_sync_en: false # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu:
        0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 3 # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 64
    blind: 1.0 # 最小距离阈值，即过滤掉0～blind范围内的点云
    timestamp_unit: 3 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    point_filter_num: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 180
    det_range: 150.0
    extrinsic_est_en: false # true: enable the online estimation of IMU-LiDAR extrinsic
    #extrinsic_T: [0.0, 0.0, 0.0]
    extrinsic_T: [0.0062530000000000001, -0.011775, 0.0076449999999999996]
    extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]

publish:
    path_en: true
    scan_publish_en: true # false: close all the point cloud output
    dense_publish_en: true # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true # true: output the point cloud scans in IMU-body-frame

max_iteration: 3
filter_size_surf: 0.5
filter_size_map: 0.5
cube_side_length: 1000
runtime_pos_log_enable: 1
# init_method: PPICP
# NDT:
# ICP:
#     max_iter: 10
# PPICP:
#     plane_dist: 0.1
#     max_iter: 10
prior:
    #prior_T: [0.3, 1.1, 1.21]
    prior_T: [3.59,2.8,0.086]
    prior_R: [1 ,0, 0,
              0 ,1, 0,
              0 ,0, 1]
